name: Deploy

on: [push]

jobs:
  Deploy: 
    runs-on: ubuntu-latest
 
    steps:  
    - name: Verificar el Ls
      run: |
        ls
        cd ../
        ls
        cd ../../
        ls
        cd ../../../
        ls

         
    - uses: actions/checkout@master
    - name: Copiar el contenido del repositorio con scp.
      uses: appleboy/scp-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "/var/www/relex-dev.com/html"
        strip_components: 1  
        overwrite: true