name: Deploy

on: [push]

jobs:
  Deploy: 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Crear Carpeta y mover archivos
      run: mkdir build &&  mv index.html build/index.html && mv assets build/assets
          
    - name: Copiar el contenido del repositorio con scp.
      uses: appleboy/scp-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build/*"
        target: "/var/www/relex-dev.com/html/"
        strip_components: 1  
        overwrite: true